### PR TITLE
chore: add reviewdog integration for prettier

### LINKED ISSUE #139: 🛠 Tooling: Add a bot that suggests auto-formatting with Prettier
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Sometimes folks make edits in an environment without Git hooks, such as the web editor (or they use `git commit --no-verify`). Their commits and PRs will have big red ❌s complaining about formatting issues. Asking them to run Prettier might be too difficult; asking them to make manual edits might be too tedious.

Let's add a bot that offers to apply Prettier fixing for them. It should explain what the formatting needs are and have something like 'react with 👍' and/or 'reply with _yes_' to trigger.

### Additional Info

This will be particularly useful for projects such as https://github.com/OpenContributionsProject/opensourcecontributionssite that are intended to have non-programmer folks participate.

### PR DESCRIPTION
**Pull request by nowyDEV**
## PR Checklist

- [x] Addresses an existing open issue: fixes #139 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Added revewdog github action that comments on formatting problems with Prettier.
There are more integrations for ESLint, TypeScript and other linters we could also make use of.

https://github.com/EPMatt/reviewdog-action-prettier

156574285-f6fd599d-af5c-470d-b23b-c7daa92d316f

### CODE REVIEW

**Comment by nowyDEV** [comment]
Looks like it will need some additional work, we will need to make a fork of https://github.com/EPMatt/reviewdog-action-prettier and rewrite it to use pnpm.

**Comment by JoshuaKGoldberg** [comment]
> fork

Huh, is there no way to get that action to support pnpm? I would think that's a better long-term strategy for them.

Also, what makes you say they don't support pnpm? I only see this in their logs:

```plaintext
...
Run $GITHUB_ACTION_PATH/script.sh
No local changes to save
reviewdog: This GitHub token doesn't have write permission of Review API [1], 
so reviewdog will report results via logging command [2] and create annotations similar to
github-pr-check reporter as a fallback.
[1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target, 
[2]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
No stash entries found.
```

**Comment by nowyDEV** [comment]
> Ooh nifty, I hadn't seen reviewdog! Looks awesome at first glance.
> 
> My biggest concern is that I wouldn't want a PR with many formatting issues to have a bagillion suggestions that each have to be accepted individually. I would hope that there's some way to accept all at once.
> 
> And, the messaging around the comments should be friendly. Ideally they'd be able to indicate what the problem is, how to fix it locally, and what the relevant tools are.
> 
> > fork
> 
> Huh, is there no way to get that action to support pnpm? I would think that's a better long-term strategy for them.
> 
> Also, what makes you say they don't support pnpm? I only see this in their logs:
> 
> ```
> ...
> Run $GITHUB_ACTION_PATH/script.sh
> No local changes to save
> reviewdog: This GitHub token doesn't have write permission of Review API [1], 
> so reviewdog will report results via logging command [2] and create annotations similar to
> github-pr-check reporter as a fallback.
> [1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target, 
> [2]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
> No stash entries found.
> ```

Here's an error that fails the workflow:
Screenshot_2023-02-23_00-04-30

They have `npm` command hard-coded in a script file, I guess we would need some kind of detection of yarn.lock, package-lock and pnpm-lock and then conditionally run install command with different package managers?
https://github.com/EPMatt/reviewdog-action-prettier/pull/35/files

**Comment by JoshuaKGoldberg** [comment]
Sounds like a good issue to file on their repo 😉 agreed

**Comment by nowyDEV** [comment]
> Sounds like a good issue to file on their repo wink agreed

Looks like they fixed the issue with latest release, the annotations are added properly https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/261/files#diff-4a8f3f01944f103fd036449fd2096a19ca487395463930310271743fb80ac0a6R12

We're lacking review permissions for github token, reviewdog can't add comments right now 
https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/4565417494/jobs/8056507401?pr=261#step:4:404

**Comment by JoshuaKGoldberg** [comment]
This action is very snazzy! I like that it posts automatically as suggestions.

Some initial feature requests on the action while this is in draft:
* Want to consolidate into just one comment - many comments (especially on larger PRs) can be quite intimidating!
* Want a way to gently explain what's going on (link to development docs)
* Want the (non-maintainer) author to be told how to click a button to accept all them, and `git pull` if needed

**Comment by JoshuaKGoldberg** [comment]
> lacking review permissions for github token

Yeah I'd recommend forking/using this template into a scratch repo you maintain & have tokens for. That way we can poke around on it without breaking things here.

**Comment by JoshuaKGoldberg** [comment]
@nowyDEV this has been sitting for a while so I'm going to close it out to keep the PR queue small. If you do end up finding/making an integration that satisfies the issue, let me know! I'd be happy to re-review. 🙂 

Thanks for sending!

**Pull request closed without merging**
