### PR TITLE
chore: update knip to new major version

### LINKED ISSUE #280: 🛠 Tooling: Try out Knip v2
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

https://github.com/webpro/knip/issues/73: Knip v2 is available to try out and looks _awesome_. Let's try it out in this repo!

Accepting PRs to upgrade Knip to v2.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by nowyDEV**
## PR Checklist

- [x] Addresses an existing open issue: fixes #280 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Updated Knip to next major version (still in alpha).
Description: https://github.com/webpro/knip/issues/73
New docs: https://github.com/webpro/knip/blob/v2/README.md

Managed to run a few quick checks:
- [x] Reports missing dependencies (tested after removing `@types/eslint`)
- [x] Reports unused files
- [x] Reports unused exports of variables/functions
- [x] Reports unused exports of type interfaces

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Awesome!

@RebeccaStevens since you put a lot of thought into this for ts-api-utils, do you want us to wait for your review on this one? (do you have time? 😄 )

**Comment by RebeccaStevens** [comment]
I don't think there's anything else that needs to change in this project for a knip update. It should just work.

Though, there's already a newer version of knip available than what this PR adds. The full release of knip 2 is planned for ["next week"](https://github.com/webpro/knip/issues/73#issuecomment-1473763200).

**Comment by JoshuaKGoldberg** [comment]
Love it! Let's wait till the full new version is out. Then :shipit:!

**Comment by JoshuaKGoldberg** [comment]
Knip v2 is released! Let's ship this! 🚀

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks @nowyDEV, as always! ✨

**Pull request merged**
