### PR TITLE
feat: add .nvmrc and `engines` key to package.json

### LINKED ISSUE #65: 🛠 Tooling: Add an .nvmrc and package.json engines
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue+label%3A%22area%3A+tooling%22) and found none that matched my issue.

### Overview

Copying from https://github.com/JoshuaKGoldberg/refined-saved-replies/issues/68: it'd be good to check in an `.nvmrc` and add an [`engines` entry in the `package.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines). Some packages only work on certain Node versions.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Pinjasaur**
## PR Checklist

- [x] Addresses an existing open issue: fixes #65
- [x] That issue was marked as [accepting prs](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

It's like https://github.com/JoshuaKGoldberg/refined-saved-replies/pull/69 but for this repo. 🙃

### CODE REVIEW

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
This looks great in general, but it's failing a lint task:

```plaintext
$ npx eslint . --max-warnings 0 --report-unused-disable-directives

template-typescript-node-package/package.json
Error:   51:2  error  Expected object keys to be in ascending order. 'engines' should be before 'version'  jsonc/sort-keys
```

This is one of the lint rules I've been meaning to bring into my other repos 😄

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 thanks!

**Comment by Pinjasaur** [comment]
Thanks @JoshuaKGoldberg! Would it be worth adding to a precommit hook locally? I personally have a tendency to "commit and forget."

**Comment by JoshuaKGoldberg** [comment]
What would the precommit hook do?

I'm wary of running ESLint in a hook because with type information it can be a little slow. But if there's a good way to only run untyped + fixable rules, that'd be nice...

**Comment by Pinjasaur** [comment]
> What would the precommit hook do?
> 
> I'm wary of running ESLint in a hook because with type information it can be a little slow. But if there's a good way to only run untyped + fixable rules, that'd be nice...

I was just thinking it could lint. 🤷🏻

I've used [`lint-staged`](https://www.npmjs.com/package/lint-staged) on a project at a previous role and it was pretty slick, even ended up using it to leverage [`shellchck`](https://github.com/gunar/shellcheck/issues/25) to lint shell scripts in the same (mono)repo. Maybe it would be worth a test/benchmark? 🙂

**Comment by JoshuaKGoldberg** [comment]
If a benchmark shows it's reasonably quick, I'm down!

We'll want to get a meaty project in. [`tslint-to-eslint-config`](https://github.com/typescript-eslint/tslint-to-eslint-config) might be a good testing ground.

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @Pinjasaur for tooling

_(whoops, I forgot I'd set this up!)_

**Pull request merged**
